#!/usr/bin/env bash

# Initialize a counter
counter=1

# Using a while loop to display "Best School" 10 times
while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ] 
    then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi

    ((counter++))
done
