#!/usr/bin/env bash
#Prints Best Shool 10 times with customization
i=1
while [ $i -ne 11 ]
do
  if [ $i -eq 9 ]
  then
    echo -e "Best School\nHi"
  else
    echo  "Best School"
  fi
  i=$(( i + 1 ))
done
