#!/usr/bin/env bash
# Loop from 1 to 10
counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "Bad luck"
	elif [ $counter -eq 8 ] 
	then
		echo "Good luck"
	else
		echo "Best School"
	fi
    ((counter++))
done
