#!/usr/bin/env bash
# Script to display content of the current directory in a specific format

for file in *
do
    if [ -f "$file" ] && [ ! -h "$file" ] && [[ $file == *-* ]]
then
        # Extract the part of the name after the first dash
        display_name=$(echo "$file" | cut -d'-' -f2-)
        echo "- $display_name"
    fi
done
