#!/usr/bin/env bash
# Connects to the server using the private key ~/.ssh/school with the user ubuntu

# Replace <server_ip> with the actual server IP address
server_ip="<server_ip>"

# Connect to the server using ssh with the specified private key
ssh -i ~/.ssh/school ubuntu@$server_ip
