#!/usr/bin/env bash
# Script to create an RSA key pair with specific requirements

# Define the key name, bit size, and passphrase
KEY_NAME="school"
BIT_SIZE=4096
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $BIT_SIZE -f $KEY_NAME -N $PASSPHRASE
